Add smart card feature
osboot/make-initrd pull request #7
Opened 2021-07-07 11:34 UTC by lo1ol

Add feature with utilities for working with smart card.
Add ability to use smart card for luks partition unlock.
Add ability to put features library inside initrd by name.

Добавил фичу утилитами для работы со смарт картами.
Добавил возможность разблокировки luks разделов с помощью ключей, лежащих на смарт-карте.
Добавил возможность класть библиотеки в initrd по их по имени.

2021-07-07 13:35 UTC, legionus requested changes
В целом выглядит хорошо, но есть некоторые замечания.

2021-07-07 13:35 UTC, legionus commented on features/luks/data/lib/uevent/handlers/085-luks
> +		local "${v%%=*}"="${v#*=}"
тут неплохо бы сделать валидацию имени переменной. Что-то типа:
```
case "$v" in
   serial=*|id=*|label=*) ;;
   *) fatal "unknown parameter: $v" ;;
esac

local "${v%%=*}"="${v#*=}"
```

2021-07-07 13:35 UTC, legionus commented on features/luks/data/lib/uevent/handlers/085-luks
> +		plymouth ask-for-password \
`id`, `application_label`, `module`, `path` можно вынести из if и использовать внутри pkcs11-tool-wrapper.

2021-07-07 13:35 UTC, legionus commented on features/luks/data/lib/uevent/handlers/085-luks
> +	keyid=${keyid#pkcs11:}
Тут ident не нарушен ?

2021-07-07 13:35 UTC, legionus commented on features/smart-card/README.md
> +SMART_CARD_PKCS11_MODULE ?= librtpkcs11ecp.so
Вот тут `?=` не нужен. Эта конструкция означает присвоить, если переменная ещё не определена. Эта конструкция полезна в `config.mk`.

2021-07-07 13:35 UTC, legionus commented on features/smart-card/data/bin/smart-card
> +wait_for_smart_card()
Где эта функция используется ?

2021-07-07 13:35 UTC, legionus commented on features/smart-card/data/etc/rc.d/init.d/pcscd
> +	if [ ! -d $IPCDIR ]
Проверь пожалуйста coding style в этом файле.

2021-07-09 08:13 UTC, lo1ol commented on features/smart-card/README.md
> +SMART_CARD_PKCS11_MODULE ?= librtpkcs11ecp.so
Я это оставил на случай, если мы задали переменную через аргументы make-initrd
```bash
make-initrd SMART_CARD_PKCS11_MODULE=librtpkcs11ecp.so
```

2021-07-09 08:13 UTC, lo1ol commented on features/smart-card/data/bin/smart-card
> +wait_for_smart_card()
пока нигде...

2021-07-09 08:14 UTC, lo1ol commented on features/smart-card/data/etc/rc.d/init.d/pcscd
> +	if [ ! -d $IPCDIR ]
оке, взял его из основного файла демона

2021-07-09 10:26 UTC, lo1ol commented on features/smart-card/data/bin/smart-card
> +wait_for_smart_card()
убрал эту функцию

2021-07-09 10:26 UTC, lo1ol commented on features/smart-card/data/etc/rc.d/init.d/pcscd
> +	if [ ! -d $IPCDIR ]
переписал по аналогии с другими сервисами

2021-07-09 10:27 UTC, lo1ol commented on features/luks/data/lib/uevent/handlers/085-luks
> +	keyid=${keyid#pkcs11:}
исправил

2021-07-09 10:27 UTC, lo1ol commented on features/luks/data/lib/uevent/handlers/085-luks
> +		plymouth ask-for-password \
исправил

2021-07-09 10:27 UTC, lo1ol commented on features/luks/data/lib/uevent/handlers/085-luks
> +		local "${v%%=*}"="${v#*=}"
исправил

2021-07-09 10:27 UTC, lo1ol commented on features/luks/data/lib/uevent/filters/lukskeys
> +	if [ "$is_pkcs11" ]; then
исправил

2021-07-09 10:27 UTC, lo1ol commented on features/luks/data/lib/uevent/filters/lukskeys
> +	if [ $1 = "pkcs11" ]; then
исправил

2021-07-09 10:42 UTC, lo1ol commented on features/smart-card/README.md
> +SMART_CARD_PKCS11_MODULE ?= librtpkcs11ecp.so
исправил

2021-07-09 10:50 UTC, legionus commented on features/luks/data/lib/uevent/handlers/085-luks
> +        local serial id label application_label module type output_file flags rc=1
Интерфейс github ужасен, но видно, что ident `local` и `export` разный.

2021-07-09 12:20 UTC, legionus approved these changes
LGTM

2021-07-12 12:24 UTC, legionus commented
Merged into for-master.

2021-07-12 12:24 UTC, closed without merging